#!/bin/bash
#檔案名 簡轉繁
#    * 需安裝套件 ： nautilus-script-manager
#    * 把檔案放在： $HOME/.gnome2/nautilus-scripts ，檔名例如為：簡轉繁，並加入執行權限。
#    * 在檔案瀏覽器中，選擇檔案按滑鼠右鍵會出現 -- 指令稿-->簡轉繁 
IFS=$'\n'
for FILENAME in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
        #取得最後檔名部份
        base_name=${FILENAME##*/}
        #取得路徑
        n_path=${FILENAME%/*}

	old=$base_name
	#簡體檔名轉換成繁體檔名
 	cat  $n_path/$old |iconv -c -f utf8 -t gb2312 | iconv -c -f gb2312 -t big5 | iconv -c -f big5 -t utf8  >  $n_path/$old.new
        rm   $n_path/$old 
        mv  $n_path/$old.new  $n_path/$old
 # 	if [ $old  !=  $new ]
 #	    	mv $n_path/$old   $n_path/$new
#             echo  $n_path/$old   $n_path/$new   >  ~/rm.log
 #	fi 

done 