#!/bin/bash
#檔案名 修改時間
#    * 需安裝套件 ： nautilus-script-manager
#    * 把檔案放在： $HOME/.gnome2/nautilus-scripts ，檔名例如為：修改時間，並加入執行權限。
#    * 在檔案瀏覽器中，選擇檔案按滑鼠右鍵會出現 -- 指令稿-->修改時間 
IFS=$'\n'
for FILENAME in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
        #取得最後檔名部份
        base_name=${FILENAME##*/}
        #取得路徑
        n_path=${FILENAME%/*}
 
				touch -c  $base_name
 				sleep 1

done 