#!/bin/bash
#檔案名 簡轉繁 (包含以下目錄)
#    * 需安裝套件 ： nautilus-script-manager
#    * 把檔案放在： $HOME/.gnome2/nautilus-scripts ，檔名例如為：簡轉繁，並加入執行權限。
#    * 在檔案瀏覽器中，選擇檔案按滑鼠右鍵會出現 -- 指令稿-->簡轉繁 
#
function ren() {
	for fn in $*
	do
        	#取得最後檔名部份
        	base_name=${fn##*/}
        	#取得路徑
        	n_path=${fn%/*}
 
		old=$base_name
		#取得字串長度
		old_len=${#old}
		#簡體檔名轉換成繁體檔名
 		#new=`echo $old |iconv -c -f utf8 -t gb2312 | iconv -c -f gb2312 -t big5 | iconv -c -f big5 -t utf8`
 		new=`echo $old |~/tools/chinese-conv.php`
 
		new_len=${#new}
		
		#名稱有變，而且字數要相同才行
		#if [ $old  !=  $new ] &&  [ $old_len -eq $new_len ] ;then
			mv $n_path/$old   $n_path/$new
			#echo  $n_path/$old   $n_path/$new   >>  ~/mv.log
		#fi         	
        done	

}	

function dr() {
#一定要加入  local ，否則會成全域變數
local ni 
for i in $* ; do
        ni=$i
        #echo  $ni  >>  ~/mv.log
 	#判斷為目錄再進入
	if [ -d $i ]   ; then

 	   fn_list=`ls -d $i/*`
 	    
	   dr  $fn_list  
	   ren $ni
  	fi
  	
	if [ -e $i ] ; then 
 
	   ren $i 
 	fi
done

}

IFS=$'\n'
for FILENAME in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
       dr  $FILENAME  
done 

